### PR TITLE
Added the husky to the project

### LINKED ISSUE #11: Add Husky hooks for linting and Prettier formatting

### PR DESCRIPTION
**Pull request by Ameerjafar**
I have added the huksy to the project with linting and the prettier.

fix: #11

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@nimit9 can you review the pr

**Comment by devsargam** [comment]
Consider adding lint-staged instead of checking for all the files. @Ameerjafar

**Comment by Ameerjafar** [comment]
@devsargam i have added it can you please check it out.

**Comment by Ameerjafar** [comment]
@nimit can you check this one.

**Pull request merged**
