### PR TITLE
Set Up Monorepo with Turborepo for Frontend and Backend Projects

### PR DESCRIPTION
**Pull request by vatan45**
The basic configuration for our monorepo, which includes both frontend and backend projects, is introduced in this PR utilising Turborepo. Key modifications have been made as follows:

issue:- #1 

Started Monorepo: Utilising Turborepo, the monorepo structure was set up to effectively handle front-end and back-end apps.
Frontend Setup: Added a React application using Tailwind CSS for style, Zustand for state management, and Vite for UI design. For routing purposes, React Router was integrated, and Jest and the React Testing Library were set up for testing.
Backend Configuration: An Express.js backend was set up, utilising Passport.js for authentication and Prisma ORM for database interactions. middleware with configurations for security, error handling, and logging. Jest was included for backend testing.
Configure TypeScript, ESLint, and Prettier settings once and use them consistently throughout the monorepo for shared development methods.
UI Elements:

### CODE REVIEW

**Comment by nimit9** [comment]
thos doesn't have common packages with ts, eslint, tialwind configs

**Comment by vatan45** [comment]
@nimit9 done sir

**Comment by vatan45** [comment]
> thos doesn't have common packages with ts, eslint, tialwind configs

done sir

**Comment by nimit9** [comment]
closing in favour of #2

**Pull request closed without merging**
