### PR TITLE
:sparkles: Add a starter monorepo for the project

### PR DESCRIPTION
**Pull request by nawinsharma**
this pr solves #1

### CODE REVIEW

**Comment by toufiqfarhan0** [comment]
react not next app

image

**Comment by nawinsharma** [comment]
@toufiqfarhan0 initialized the monorepo with frontend (react+vite) and backend folder (using ts as a language)

**Comment by nawinsharma** [comment]
hey, @nimit9  Added all the requirements as suggested from readme file.

**Comment by nawinsharma** [comment]
This pr solves the issue #1 
I have tested it on my end. 

Added a Monorepo Structure with Turborepo

- **frontend:** React with Vite
- **State Management:** Zustand for state management.
- **UI Library:** Tailwind CSS + ShadCN for styling components.
- **Routing:** React Router for routing needs.
- **Testing:** Jest and React Testing Library for unit and integration tests
- **backend:** Express.js for handling HTTP requests and routing.
- **Database:** Prisma ORM for database interactions (PostgreSQL as the database).
- **Authentication:** Passport.js authentication.
- **Middleware:** Include common middleware for logging, error handling, and security.
- **Testing:** Use Jest for backend testing.
- **Build and Dev:** Integrated with Turborepo for streamlined development.

**Comment by nimit9** [comment]
need db as a separate package, which will have prisma

**Comment by nawinsharma** [comment]
@nimit9 , added db in package folder which contains prisma client and which is used by all folders in /apps.

**Comment by nimit9** [comment]
FE shouldn't use db

**Comment by nawinsharma** [comment]
@nimit9 removed, now db is accessible to only backend

**Comment by nawinsharma** [comment]
hey @nimit9 , all the tasks are completed now.

**Comment by nimit9** [comment]
LGTM for now, will merge and test it out, will add issues if something extra is needed

**Pull request merged**
